### ISSUE TITLE
Filter Multiple Objects Average Ratings and Order in Ascending Order

### ISSUE THREAD

**Issue by bobozar** [wildfish/django-star-ratings#133]
I want to filter ratings of multiple objects in a tuple, check the overall average rating for each object id, and return object ids with the highest average rating.

I did this but not returning any result.

```
from star_ratings.models import Rating

video_post = Foam.objects.all()
 if video_post:
        dem_ds = []
        for hu in video_post:
            dem_ds.append(hu.id)
            
        tup_videos = tuple(dem_ds)

        high_rated_vids = Rating.objects.filter(object_id__in=tup_videos)

        top_rated=(high_rated_vids.order_by('-average').values_list('average', flat=True).distinct())

        top_by_rated=(top_rated.order_by('-average').filter(average__in=top_rated))

```
What am I missing?

**Comment by OmegaDroid** [comment]
Hi @bobozar,

This depends on how you are using rating but I think there are some issues with your code.

Firstly because of how the ratings are attached to multiple content types `Rating.objects.filter(object_id__in=tup_videos)` could give incorrect results. If I have ratings for 2 models `Foo` and `Bar` then running the above query would give results for both `Foo` and `Bar` objects with ids in `tup_videos`. If you are only rating one model then this isn't an issue but to get all ratings for the `Foam` model as you seem to be, running `Rating.objects.filter(content_type=ContentType.objects.get_for_model(Foam))` would be better.

Secondly you seem to be doing some unnecessary filtering, unless I'm mistaken `top_rated.order_by('-average').filter(average__in=top_rated)` does nothing, you are filtering a query set (`top_rated`) by the same queryset.

If you want to get a list of highest rated `Foam` ids objects I would run 

```
Rating.objects.filter(content_type=ContentType.objects.get_for_model(Foam)) \
    .order_by('-average') \
    .values_list('object_id', flat=True)
```

If this returns nothing I would check that rating for the model actually exist. The ratings objects are not created until someone rates something so if there have not yet been any ratings for `Foam` objects this will return an empty queryset.
