### ISSUE TITLE
ForeignKey Relationship Not Working

### ISSUE THREAD

**Issue by bobozar** [wildfish/django-star-ratings#134]
I need to get the attributes of the foreign key objects rated. 'VideoPost' is a ForeignKey here.

So let's say I do, 

`mvp = Ratings.objects.filter(object_id=12)`

When I do ,

```
{% for m in mvp %}
   {{ m.object_id.videopost.name}}
{% empty %}
 <p> Nothing here. </p>
{% endfor %}
```

It won't return anything.  How do I go about foreign key relationship?

**Comment by OmegaDroid** [comment]
Hi @bobozar 

The issue here is you are using `m.object_id`, this is the primary key of the related object and not the object itself. To get the object you need to reference `m.content_object`.

For the generic relationship we follow the pattern given here https://docs.djangoproject.com/en/2.0/ref/contrib/contenttypes/#generic-relations.
