### ISSUE TITLE
Awful instruction

### ISSUE THREAD

**Issue by wena77** [wildfish/django-star-ratings#147]
it's absolutely incomprehensible how to use it after installation! Your insrtuctions in "USAGE" are too short!  i'm changing "object" in "{% ratings object %}" on the name of my model, but it doesn't work. Can you give deeper explanations how to use it, please?

**Comment by OmegaDroid** [comment]
Hi @wena77, 

It would be good to figure out where you are going wrong so that we can figure out exactly where the docs fall short, adding the tag to the template passing the object in your context as `object` should be all you need.

**Comment by elshaddae** [comment]
@OmegaDroid It is true that the documentation is totally not straight forward. If you follow all the instructions the app won't work.

**Comment by rolo** [comment]
Hiya. I've followed the instructions in the getting started and it seem that the info may need updating for the new Django default `urls.py` since Django 2.0.

If this is the case you should be able to get things working by changing the line in `urls.py` to:

```
url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
```

And adding the following import at the top of the file.

```
from django.conf.urls import include, url
```

Please let me know if this doesn't help.

I'll add a new issue to update the docs.
