### ISSUE TITLE
all objects from Foo are not show for review

### ISSUE THREAD

**Issue by subrush** [wildfish/django-star-ratings#153]
Hi there i need help on the following
while i am testing the demo i was not able to get all list of object (only view 'foo bar baz'). i have checked before login and after loged in. where shall i do the modification. is it inside view.py  FooView class 
class FooView(DetailView):
    modelz = Foo
    def get_object(self, queryset=None):
        obj, created = self.model.objects.get_or_create(bar='foo bar baz')       
        return obj

**Comment by radiac** [comment]
Hi @subrush,

We're not quite clear on what you're trying to achieve - are you trying to show a list of `Foo` objects with their ratings?

The only `Foo` view in the demo is a simple `DetailView`, which just has a `get_object` method to ensure the demo object (`'foo bar baz'`) is in the database so that the `ratings` template tag can do its thing.

From what you're saying, you want to list all the `Foo` objects? If so, you're probably after a `ListView` ((django docs](https://docs.djangoproject.com/en/2.1/ref/class-based-views/generic-display/#listview)); you can then show ratings in the template for each object as described in the documentation.

Does that help, or have we misunderstood your question?

Thanks!

**Comment by radiac** [comment]
Hi @subrush,

You can supply your own ratings model (see the documentation for details), and use that to override the `calc` method. If you look at the [source for the default](https://github.com/wildfish/django-star-ratings/blob/develop/star_ratings/models.py#L92-L100) you'll see it sets the count, total and average, so you can just change the way those are calculated in your own method to accomplish the weighting.
