### ISSUE TITLE
Work fine when running on a local host, but gives a CSRF error when deploying on PythonAnywhere

### ISSUE THREAD

**Issue by whimsy94** [wildfish/django-star-ratings#161]
![Capture1](https://user-images.githubusercontent.com/46629658/54764040-ed79e880-4bee-11e9-99fe-dd107f0dbb48.JPG)
![Capture2](https://user-images.githubusercontent.com/46629658/54764041-ee127f00-4bee-11e9-80cf-4e23d410fdc7.JPG)

**Comment by OmegaDroid** [comment]
Hi @whimsy94 I don't have any experience with python anywhere so its hard to say. Have you set the `ALLOWED_HOSTS` in your settings file? 

This seems to be an issue with your settings and how it is handled in python anywhere rather than an issue with the ratings app, could you try adding a basic form that posts data to a different url and see if you have the same error.

**Comment by jaborsm** [comment]
Hi there...I am facing similar issue, how did you fixed it ? @whimsy94

Really appreciate it
