### ISSUE TITLE
Usage instructions don't work with new default urls.py since Django 2.0

### ISSUE THREAD

**Issue by rolo** [wildfish/django-star-ratings#164]
We should update the instructions so that they work in a backwards compatible way.

**Comment by OAkala** [comment]
Hey, I just tried following the instructions for using this package and I noticed that the syntax for the url in url.py is not supported in django 2.xx. I tried to edit it as the following:
`path('ratings/', include('star_ratings.urls')),`
But now I am getting the following error:

> django.urls.exceptions.NoReverseMatch: 'ratings' is not a registered namespace

Please I need advice

**Comment by jamesoutterside** [comment]
Hi @OAkala you need to include the namespace for ratings e.g. 

`path('ratings/', include('star_ratings.urls', namespace='ratings')),`

docs updated with #185

**Comment by OAkala** [comment]
Thanks

**Comment by mwikya** [comment]
I am getting a similar error with the following message:

Reverse for 'rate' with arguments '(6, UUID('64767a50-b788-48b5-aed1-7599e9b2bb74'))' not found. 1 pattern(s) tried: ['ratings/(?P<content_type_id>\\d+)/(?P<object_id>\\d+)/']

**Comment by mwikya** [comment]
Solved updating my settigns with 
STAR_RATINGS_OBJECT_ID_PATTERN = r'[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}'

the documentation is a little bit outdated I guess, as it doesn't cover most issues I faced, had to dig deeper into the code

**Comment by jamesoutterside** [comment]
Hi @mwikya 

Thanks for the report, I've had a look, it looks like the docs @ https://django-star-ratings.readthedocs.io/en/latest/?badge=latest/ are out of sync, we'll take a look at that. 

In the meantime, could you try installing again from the docs in the [README.rst](https://github.com/wildfish/django-star-ratings/blob/develop/README.rst)? I've just set up a demo project from scratch, with those instructions and all worked as expected. 

As a note out the box you shouldn't need to change `STAR_RATINGS_OBJECT_ID_PATTERN`, but that could have been caused by the docs confusion, apologies if so. 

That final issue RE path indicates that the JS is not working as expected if you still encounter that after the steps above, let us know your setup and we will take a look. 

Thanks

**Comment by patroqueeet** [comment]
> Solved by updating settings with
> STAR_RATINGS_OBJECT_ID_PATTERN = r'[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}'
> 
> and then I bumped into this: This QueryDict instance is immutable
> ![image](https://user-images.githubusercontent.com/28346039/82213067-3d9c2a00-991c-11ea-9bad-eb9d8a3fdcf0.png)
> 
> Can that line be changed to return_url = data.get('next', '/')
> 
> the documentation is a little outdated I guess and doesn't cover most issues I faced, had to dig deeper into the actual code

Running into the immutable error too... pls advice how to fix!
