### ISSUE TITLE
star icons not scaling to args size

### ISSUE THREAD

**Issue by northscope** [wildfish/django-star-ratings#63]
Rating stars not scaling with width and height args set in template tags.
`<span class="pull-right">{% ratings obj 20 20 %}</span>`

I'm using bootstrap 3 for the frontend Here is my result, is this a bug? 
![e333](https://cloud.githubusercontent.com/assets/15750150/12737555/7e5c4fe8-c9be-11e5-8f97-a3ba1a2d0e34.png)

**Comment by jonashagstedt** [comment]
The images doesn't scale. 
The width and height property are there in case you want to use your own sprite sheet and it has a different size to the original.

E.g you create a sprite sheet with icons that are 20x20.

Since it's using a sprite sheet rather than individual images you can't really set the background size to `
background-size: 100% 100%;` either.

I think the simplest solution would be:

1.  create "/static/star-ratings/images/" in your project
2.  copy *https://raw.githubusercontent.com/wildfish/django-star-ratings/develop/star_ratings/static/star-ratings/images/stars.png* into the directory
3.  resize the image to 60x20

**Comment by northscope** [comment]
@jonashagstedt your solution works great. Thank you.
