### ISSUE TITLE
order_by('ratings__average') sorts lowest to highest

### ISSUE THREAD

**Issue by mpollachek** [wildfish/django-star-ratings#92]
I'm a newbie here, but when I chain .order_by('ratings__average') on my filter, it sorts from lowest rated to highest rated.  Is this a bug?  if not, how can I reverse the sort order?

**Comment by mpollachek** [comment]
nevermind-I can use .order_by('-ratings__average') to sort from highest rated to lowest rated.  I still think it would make more sense for that to be the default.

**Comment by OmegaDroid** [comment]
Hi @mpollachek. 

The issue with making it the default is that it needs to be set on your model rather than on the rating and we wouldn't want to change the default ordering behind the scenes as this would likely be confusing. 

You can set this as the default ordering for your model by adding it to the meta class though. Something like this should do the trick:

```
class MyModel(models.Model):
    class Meta:
        ordering = ('-ratings_average',  )
```

The docs are here https://docs.djangoproject.com/en/1.10/ref/models/options/#ordering

**Comment by mpollachek** [comment]
Thanks @OmegaDroid for your reply.  Also Thanks for the app.  I am using it in my class project :)
